import 'dart:io';

/// A temporary workspace this preparation created and exclusively owns.
/// No caller-supplied path can acquire recursive-delete ownership.
class BinaryExportArtifact {
  BinaryExportArtifact._(this._directory, this._parent, this.name);

  final Directory _directory;
  final String _parent;
  final String name;

  String get path => '${_directory.path}/$name';
  Directory get directory => _directory;

  static Future<BinaryExportArtifact> create({
    required Directory temporaryDirectory,
    required String name,
  }) async {
    if (!isSafeExportFileName(name)) throw ArgumentError.value(name, 'name');
    final String parent = await temporaryDirectory.resolveSymbolicLinks();
    final Directory directory = await Directory(parent)
        .createTemp('hearth-archive-');
    return BinaryExportArtifact._(directory, parent, name);
  }

  Future<void> discard() async {
    // Both the created directory and its parent must still identify the
    // workspace we own. In particular, never follow a substituted symlink.
    if (await FileSystemEntity.type(_directory.path, followLinks: false) !=
        FileSystemEntityType.directory) {
      return;
    }
    if (_directory.parent.path != _parent ||
        !_directory.path.startsWith(
          '$_parent${Platform.pathSeparator}hearth-archive-',
        ) ||
        await _directory.resolveSymbolicLinks() != _directory.path) {
      throw StateError('Archive temporary directory no longer matches.');
    }
    await _directory.delete(recursive: true);
  }
}

/// Archive paths are generated by us. External titles and identifiers never
/// become path components without a separate safe generated prefix.
bool isSafeExportFileName(String name) =>
    RegExp(r'^[a-zA-Z0-9][a-zA-Z0-9._-]*$').hasMatch(name) &&
    name != '.' &&
    name != '..';

class ArchivePreparationCancelled implements Exception {
  const ArchivePreparationCancelled();
}

void ensureArchiveCurrent(bool Function()? isCurrent) {
  if (isCurrent != null && !isCurrent()) {
    throw const ArchivePreparationCancelled();
  }
}
