// dart format width=80
// GENERATED BY drift_dev, DO NOT MODIFY.
// ignore_for_file: type=lint,unused_import
//
import 'package:drift/drift.dart';
import 'package:drift/internal/migrations.dart';

import 'schema_v25.dart' as v25;

class GeneratedHelper implements SchemaInstantiationHelper {
  @override
  GeneratedDatabase databaseForVersion(QueryExecutor db, int version) {
    switch (version) {
      case 25:
        return v25.DatabaseAtV25(db);
      default:
        throw MissingSchemaException(version, versions);
    }
  }

  static const versions = const [25];
}
