import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hearth/core/build_info.dart';
import 'package:hearth/data/local/cook_session_store.dart';
import 'package:hearth/data/local/hearth_database.dart';
import 'package:hearth/data/local/plan_store.dart';
import 'package:hearth/domain/planning/target_schedule.dart';

import 'generated_migrations/schema.dart';

/// A real historical upgrade, from a real old schema (CLAUDE.md rule 8).
///
/// `migration_replay_test.dart` winds `user_version` back on today's tables,
/// which is the *half-applied* state an interrupted upgrade leaves — the
/// state that once stopped the app opening its own database. It is not an old
/// database, and it said so.
///
/// This is the other half, and it only became possible when a second snapshot
/// existed: drift builds a database at v25 exactly as v25 was, runs the real
/// migration against it, and checks the result against v26 exactly as v26 is.
/// A step that creates a table the old schema already had, or forgets one the
/// new schema needs, fails here rather than on somebody's phone.
///
/// Every recorded version is wound forward to the one the code claims today,
/// rather than one hard-coded pair. The pair was v25 → v26, written when 26
/// was the newest — so v27 shipped without ever being exercised here, and the
/// sentence above was not true. It is now: a new snapshot is picked up by the
/// loop, and so is the step that produced it.
///
/// Winding forward to *today* rather than to the next version is also the only
/// state a phone can be in. Nothing upgrades from 25 to 26 and stops; it opens
/// the app once and arrives at the current version through every step at
/// once, which is exactly what this runs.
void main() {
  /// The version the code claims. Read rather than written down, so the loop
  /// below cannot fall behind a bump the way the old hard-coded pair did.
  ///
  /// [BuildInfo.schemaVersion] rather than a database's own: `build_info_test`
  /// holds the two equal, `migration_replay_test` already drives its loop off
  /// this one, and opening a database here to read a constant would leave it
  /// open — there is no test to hang `addTearDown` on at file scope, and an
  /// unclosed connection in this suite hangs the run rather than failing it.
  const int current = BuildInfo.schemaVersion;

  // Every snapshot the repository actually has, rather than a number written
  // down here — `GeneratedHelper.versions` is regenerated by the second of
  // rule 8's two commands, so a new dump joins this loop on its own.
  for (final int from in GeneratedHelper.versions) {
    if (from >= current) continue;
    test(
      'v$from upgrades to v$current and matches the recorded schema',
      () async {
        final SchemaVerifier verifier = SchemaVerifier(GeneratedHelper());

        final InitializedSchema old = await verifier.schemaAt(from);
        final HearthDatabase db = HearthDatabase.forTesting(
          old.newConnection(),
        );
        addTearDown(db.close);

        await verifier.migrateAndValidate(db, current);
      },
    );
  }

  test('and a database already holding rows keeps them', () async {
    // The half that matters on a phone. A schema that validates is not the
    // same as a schema that kept the year of logs already in it, and an
    // additive step that quietly rebuilt a table would pass the check above.
    final SchemaVerifier verifier = SchemaVerifier(GeneratedHelper());
    final InitializedSchema old = await verifier.schemaAt(25);

    old.rawDatabase.execute(
      'INSERT INTO recipes (id, household_id, title, servings, kind, '
      'is_deleted, updated_at) VALUES '
      "('r1', 'h1', 'Weeknight chilli', 4, 'cooked', 0, 0)",
    );

    final HearthDatabase db = HearthDatabase.forTesting(old.newConnection());
    addTearDown(db.close);
    await verifier.migrateAndValidate(db, current);

    final List<RecipeRow> kept = await db.select(db.recipes).get();
    expect(kept.single.title, 'Weeknight chilli');
  });

  test('v30 keeps saved directions and starts ingredients unchecked', () async {
    final SchemaVerifier verifier = SchemaVerifier(GeneratedHelper());
    final InitializedSchema old = await verifier.schemaAt(30);
    final DateTime now = DateTime.utc(2026, 10, 1, 18);
    old.rawDatabase.execute(
      'INSERT INTO cook_sessions (recipe_id, current_step, checked_step_ids, updated_at) '
      'VALUES (?, ?, ?, ?)',
      <Object?>[
        'dinner',
        2,
        '["step-1", "step-2"]',
        now.millisecondsSinceEpoch ~/ 1000,
      ],
    );
    final HearthDatabase db = HearthDatabase.forTesting(old.newConnection());
    addTearDown(db.close);
    await verifier.migrateAndValidate(db, current);
    final StoredCookProgress saved = (await CookSessionStore(db)
        .read('dinner', now: now))!;
    expect(saved.currentStep, 2);
    expect(saved.checkedStepIds, <String>{'step-1', 'step-2'});
    expect(saved.checkedIngredientIds, isEmpty);
  });

  test(
    'v29 weekly targets remain weekly choices after continuity is added',
    () async {
      final SchemaVerifier verifier = SchemaVerifier(GeneratedHelper());
      final InitializedSchema old = await verifier.schemaAt(29);
      final DateTime monday = DateTime(2026, 9, 28);
      old.rawDatabase.execute(
        'INSERT INTO macro_targets (id, user_id, week_start_date, kcal, '
        'protein_g, carb_g, fat_g, fiber_g, sodium_mg, cholesterol_mg, updated_at) '
        'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
        <Object?>[
          'saved-week',
          'me',
          monday.millisecondsSinceEpoch ~/ 1000,
          2000,
          120,
          230,
          70,
          null,
          0,
          250,
          0,
        ],
      );
      final HearthDatabase db = HearthDatabase.forTesting(old.newConnection());
      addTearDown(db.close);
      await verifier.migrateAndValidate(db, current);
      final PlanStore store = PlanStore(db);
      final ResolvedTargets currentWeek = await store.targetResolutionFor(
        userId: 'me',
        date: monday,
      );
      expect(currentWeek.source, TargetSource.exactWeek);
      expect(currentWeek.targets!.fiberG, isNull);
      expect(currentWeek.targets!.sodiumMg, 0);
      expect(currentWeek.targets!.cholesterolMg, 250);
      expect(
        await store.targetsFor(userId: 'me', date: DateTime(2026, 10, 5)),
        isNull,
      );
      expect(await db.select(db.ongoingMacroTargets).get(), isEmpty);
    },
  );
}
